Data Analytics III 
1. Implement Simple Naïve Bayes classification algorithm using Python/R on iris.csv dataset. 
2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall on the given dataset

In [93]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [94]:
df =  pd.read_csv('Iris.csv')

df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [95]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [96]:
df.shape

(150, 6)

In [97]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [98]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [99]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,classification_report

from sklearn.naive_bayes import GaussianNB

In [100]:
x = df[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]]
y = df[["Species"]].values.reshape(-1,1)

scaler = StandardScaler()
x =scaler.fit_transform(x)



In [101]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=42)



In [102]:
model = GaussianNB()
model.fit(X_train,y_train)

c:\Users\Adesh Mandhare\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [103]:
pred_y  = model.predict(X_test)


In [104]:
cf=confusion_matrix(y_test,pred_y)

print(cf)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [105]:
tp_1 = cf[0][0]
fp_1 = cf[1][0]+cf[2][0]
fn_1 = cf[0][1]+cf[0][2]
tn_1 =cf.sum()-tp_1-fp_1-fn_1

In [106]:
tp_2 = cf[1][1]
fp_2 = cf[0][1]+cf[2][1]
fn_2 = cf[1][0]+cf[1][2]
tn_2 = cf.sum()- tp_2 - fp_2 - fn_2


In [107]:
print(f"Accuracy score is {accuracy_score(y_test, pred_y)}")

Accuracy score is 1.0


In [108]:
print(f"Error rate is {1 - accuracy_score(y_test, pred_y)}")

Error rate is 0.0


In [109]:
print(f"Precision score is {precision_score(y_test, pred_y, average='macro')}")

Precision score is 1.0


In [110]:
print(f"Recall score is {recall_score(y_test, pred_y, average='macro')}")

Recall score is 1.0


In [111]:
print(classification_report(y_test, pred_y))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

